class CellStandards():

    sorted_cell_parameters = ['a', 'b/a', 'c/a', 'alpha', 'beta', 'gamma']


class VaspStandards():
    # Parameters to that will be tracked in parameterized model
    sorted_calc_parameters = ['xc', 'encut', 'nbands', 'ispin', 'kspacing',
                              'kgamma', 'ismear', 'sigma', 'ibrion', 'isif',
                              'nsw', 'nelm', 'ediff', 'prec', 'algo', 'lwave']

    u_parameters = ['ldau', 'lmaxmix', 'ldautype', 'ldau_luj']

    """Parameters are heavily inspired by MP standard settings at
    https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/MPRelaxSet.yaml
    """

    calc_parameters = {'xc': 'pbe',
                       'encut': 520,  # energy cutoff for plane waves
                       'nbands': -5,  # number of bands / empty bands
                       'ispin': 2,  # number of spins
                       'kspacing': 20,  # kspacing in units of 0.01
                       'kgamma': True,  # include gamma point
                       'ismear': -5,  # smearing function
                       'sigma': 5,  # k-point smearing in units of 0.01
                       'ibrion': 2,  # ion dynamics
                       'isif': 3,  # degrees of freedom to relax
                       'nsw': 99,  # maximum number of ionic steps
                       'nelm': 100,  # maximum number of electronic steps
                       'ediff': 10,  # sc accuracy in units of 1e-6
                       'prec': 'Accurate',  # Precision
                       'algo': 'Fast',  # optimization algorithm
                       'lwave': False,  # save wavefunctions or not
                       'ldau': True,  # USE U
                       'lmaxmix': 4,
                       'ldautype': 2,
                       'ldau_luj': {}
                       }

    # parameters are submitted as an integer,
    # that will be multiplied by the standard below
    calc_decimal_parameters = {'kspacing': 0.01,
                               'sigma': 0.01,
                               'ediff': 1e-6,
                               # 'ediffg': -0.001,
                               }

    paw_potentials = {'Li': '_sv',
                      'Na': '_pv',
                      'K': '_sv',
                      'Ca': '_sv',
                      'Sc': '_sv',
                      'Ti': '_sv',
                      'V': '_sv',
                      'Cr': '_pv',
                      'Mn': '_pv',
                      'Ga': '_d',
                      'Ge': '_d',
                      'Rb': '_sv',
                      'Sr': '_sv',
                      'Y': '_sv',
                      'Zr': '_sv',
                      'Nb': '_sv',
                      'Mo': '_sv',
                      'Tc': '_pv',
                      'Ru': '_pv',
                      'Rh': '_pv',
                      'In': '_d',
                      'Sn': '_d',
                      'Cs': '_sv',
                      'Ba': '_sv',
                      'Pr': '_3',
                      'Nd': '_3',
                      'Pm': '_3',
                      'Sm': '_3',
                      'Eu': '_2',
                      'Gd': '_3',
                      'Tb': '_3',
                      'Dy': '_3',
                      'Ho': '_3',
                      'Er': '_3',
                      'Tm': '_3',
                      'Yb': '_2',
                      'Lu': '_3',
                      'Hf': '_pv',
                      'Ta': '_pv',
                      'W': '_sv',
                      'Tl': '_d',
                      'Pb': '_d',
                      'Bi': '_d',
                      'Po': '_d',
                      'At': '_d',
                      'Fr': '_sv',
                      'Ra': '_sv'}


class EspressoStandards():
    # Espresso parameters to that will be tracked in parameterized model
    sorted_calc_parameters = ['xc', 'encut', 'nbands', 'ispin', 'kspacing',
                              'kgamma', 'ismear', 'sigma', 'ibrion', 'isif',
                              'nsw', 'nelm', 'ediff', 'prec', 'algo', 'lwave',
                              'ldau', 'ldautype']


class CommonCalc():
    """+U values"""
    U_trickers = ['O', 'F']  # Oxides and Flourides will have +U
    U_luj = {'Au': {'L': -1, 'U': 0.0, 'J': 0.0},
             'C':  {'L': -1, 'U': 0.0, 'J': 0.0},
             'Cu': {'L': -1, 'U': 0.0, 'J': 0.0},
             'H':  {'L': -1, 'U': 0.0, 'J': 0.0},
             'Ir': {'L': -1, 'U': 0.0, 'J': 0.0},
             'O':  {'L': -1, 'U': 0.0, 'J': 0.0},
             'F':  {'L': -1, 'U': 0.0, 'J': 0.0},
             'Co': {'L': 2, 'U': 3.32, 'J': 0.0},
             'Cr': {'L': 2, 'U': 3.7, 'J': 0.0},  # Meng U: 3.5
             'Fe': {'L': 2, 'U': 5.3, 'J': 0.0},  # 'U': 4.3
             'Mn': {'L': 2, 'U': 3.9, 'J': 0.0},  # 'U': 3.75
             'Mo': {'L': 2, 'U': 4.38, 'J': 0.0},
             'Nb': {'L': 2, 'U': 4.00, 'J': 0.0},
             'Ni': {'L': 2, 'U': 6.2, 'J': 0.0},  # 'U': 6.45
             'Sn': {'L': 2, 'U': 3.5, 'J': 0.0},
             'Ta': {'L': 2, 'U': 4.00, 'J': 0.0},
             'Ti': {'L': 2, 'U': 3.00, 'J': 0.0},
             'V':  {'L': 2, 'U': 3.25, 'J': 0.0},
             'W':  {'L': 2, 'U': 6.2, 'J': 0.0},  # 'U': 2.0
             'Zr': {'L': 2, 'U': 4.00, 'J': 0.0},
             'Ce': {'L': 3, 'U': 4.50, 'J': 0.0}}

    U_metals = list(U_luj.keys())
    for U in U_trickers:
        U_metals.remove(U)

    initial_magnetic_moments = {'Ce': 5,
                                'Co': 5,
                                'Cr': 5,
                                'Fe': 5,
                                'Mn': 5,
                                'Mo': 5,
                                'Ni': 5,
                                'V': 5,
                                'W': 5}


class CrystalStandards():

    """Reference structures for formation energies, taken from 
    Materials Project.
    Most metals falls in the standard crystal structures:
    hcp: 194
    fcc: 225
    bcc: 229
    """

    standard_lattice_mp = {
        'Li': {'name': 'A_1_a_229',
               'spacegroup': 229,
               'wyckoffs': ['a'],
               'species': ['Li']},
        'Be': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Be']
               },
        'Na': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Na']
               },
        'Mg': {'name': 'A_3_ac_166',
               'spacegroup': 166,
               'wyckoffs': ['a', 'c'],
               'species': ['Mg', 'Mg'],
               'parameters': [{'name': 'a', 'value': 3.2112466672290045},
                              {'name': 'c/a', 'value': 7.139511029771984},
                              {'name': 'zc1', 'value': 0.2222079999999999}]},
        'Al': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Al']},
        'K':  {'name': 'A_20_cd_213',
               'spacegroup': 213,
               'wyckoffs': ['c', 'd'],
               'species': ['K', 'K'],
               'parameters': [{'name': 'a', 'value': 11.435131},
                              {'name': 'xc0', 'value': 0.062133},
                              {'name': 'yd1', 'value': 0.202742}]},
        'Rb': {'name': 'A_29_acg2_217',
               'spacegroup': 217,
               'wyckoffs': ['a', 'c', 'g', 'g'],
               'species': ['Rb', 'Rb', 'Rb', 'Rb'],
               'parameters': [{'name': 'a', 'value': 17.338553},
                              {'name': 'xc1', 'value': 0.817731},
                              {'name': 'xg2', 'value': 0.639646},
                              {'name': 'zg2', 'value': 0.042192},
                              {'name': 'xg3', 'value': 0.09156399999999998},
                              {'name': 'zg3', 'value': 0.2818120000000004}]},
        'Ca': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Ca']},
        'Sr': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Sr']},
        'Sc': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Sc']},
        'V': {'name': 'A_2_c_194',
              'spacegroup': 194,
              'wyckoffs':  ['c'],
              'species': ['V']},
        'La': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['La']},
        'Ti': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Ti']},
        'Zr': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Zr']},
        'Hf': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Hf']},
        'V': {'name': 'A_1_a_229',
              'spacegroup': 229,
              'wyckoffs': ['a'],
              'species': ['V']},
        'Nb': {'name': 'A_1_a_166',
               'spacegroup': 166,
               'wyckoffs': ['a'],
               'species': ['Nb']},
        'Ta': {'name': 'A_1_a_229',
               'spacegroup': 229,
               'wyckoffs': ['a'],
               'species': ['Ta']},
        'Cr': {'name': 'A_1_a_229',
               'spacegroup': 229,
               'wyckoffs': ['a'],
               'species': ['Cr']},
        'Mo': {'name': 'A_1_a_229',
               'spacegroup': 229,
               'wyckoffs': ['a'],
               'species': ['Mo']},
        'W': {'name': 'A_1_a_229',
              'spacegroup': 229,
              'wyckoffs': ['a'],
              'species': ['W']},
        'Mn': {'name': 'A_29_acg2_217',  # magnetic
               'spacegroup': 217,
               'wyckoffs': ['a', 'c', 'g', 'g'],
               'species': ['Mn', 'Mn', 'Mn', 'Mn'],
               'parameters': [{'name': 'a', 'value': 8.618498},
                              {'name': 'xc1', 'value': 0.818787},
                              {'name': 'xg2', 'value': 0.643796},
                              {'name': 'zg2', 'value': 0.035468},
                              {'name': 'xg3', 'value': 0.9109409999999998},
                              {'name': 'zg3', 'value': 0.282544}]},
        'Fe': {'name': 'A_1_a_229',
               'spacegroup': 229,
               'wyckoffs': ['a'],
               'species': ['Fe']},  # magnetic
        'Tc': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Tc']},
        'Re': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Re']},
        'Ru': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Ru']},
        'Os': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Os']},
        'Co': {'name': 'A_2_c_194',  # magnetic
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Co']},
        'Rh': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Rh']},
        'Ir': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Ir']},
        'Ni': {'name': 'A_1_a_225',  # magnetic
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Ni']},
        'Pd': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Pd']},
        'Pt': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Pt']},
        'Cu': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Cu']},
        'Ag': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Ag']},
        'Au': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Au']},
        'Zn': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Zn']},
        'Cd': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Cd']},
        'Hg': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Hg']},
        'Ga': {'name': 'A_4_f_64',
               'spacegroup': 64,
               'wyckoffs': ['f'],
               'species': ['Ga']},
        'In': {'name': 'A_3_ac_166',
               'spacegroup': 166,
               'wyckoffs': ['a', 'c'],
               'species': ['In', 'In'],
               'parameters': [{'name': 'a', 'value': 3.3328619310176943},
                              {'name': 'c/a', 'value': 7.623639840442314},
                              {'name': 'zc1', 'value': 0.22166400000000003}]},
        'Tl': {'name': 'A_2_c_194',
               'spacegroup': 194,
               'wyckoffs':  ['c'],
               'species': ['Tl']
               },
        'Si': {'name': 'A_2_a_227',
               'spacegroup': 227,
               'wyckoffs': ['a'],
               'species': ['Si']},
        'Ge': {'name': 'A_2_a_227',
               'spacegroup': 227,
               'wyckoffs': ['a'],
               'species': ['Ge']},
        'Sn': {'name': 'A_2_a_227',
               'spacegroup': 227,
               'wyckoffs': ['a'],
               'species': ['Sn']},
        'Pb': {'name': 'A_1_a_225',
               'spacegroup': 225,
               'wyckoffs': ['a'],
               'species': ['Pb']},
        'As': {'name': 'A_2_c_166',
               'spacegroup': 166,
               'wyckoffs': ['c'],
               'species': ['As']},
        'Sb': {'name': 'A_2_c_166',
               'spacegroup': 166,
               'wyckoffs': ['c'],
               'species': ['Sb']},
        'Bi': {'name': 'A_2_c_166',
               'spacegroup': 166,
               'wyckoffs': ['c'],
               'species': ['Bi']},
        'Se': {'name': 'A_64_e16_14', 'spacegroup': 14,
               'wyckoffs': ['e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e',
                            'e', 'e', 'e', 'e', 'e', 'e'],
               'species': ['Se', 'Se', 'Se', 'Se', 'Se', 'Se', 'Se', 'Se',
                           'Se', 'Se', 'Se', 'Se', 'Se', 'Se', 'Se', 'Se'],
               'parameters': [{'name': 'a', 'value': 15.739181},
                              {'name': 'b/a', 'value': 0.9726696706772735},
                              {'name': 'c/a', 'value': 0.6451328742335684},
                              {'name': 'beta', 'value': 94.0428681461934},
                              {'name': 'xe0', 'value': 0.986572},
                              {'name': 'ye0', 'value': 0.593959},
                              {'name': 'ze0', 'value': 0.23545999999999978},
                              {'name': 'xe1', 'value': 0.984712},
                              {'name': 'ye1', 'value': 0.214049},
                              {'name': 'ze1', 'value': 0.12086899999999978},
                              {'name': 'xe2', 'value': 0.913585},
                              {'name': 'ye2', 'value': 0.675372},
                              {'name': 'ze2', 'value': 0.828421},
                              {'name': 'xe3', 'value': 0.906751},
                              {'name': 'ye3', 'value': 0.009713},
                              {'name': 'ze3', 'value': 0.847639},
                              {'name': 'xe4', 'value': 0.814616},
                              {'name': 'ye4', 'value': 0.142437},
                              {'name': 'ze4', 'value': 0.4519159999999999},
                              {'name': 'xe5', 'value': 0.806848},
                              {'name': 'ye5', 'value': 0.690537},
                              {'name': 'ze5', 'value': 0.978908},
                              {'name': 'xe6', 'value': 0.769548},
                              {'name': 'ye6', 'value': 0.047426},
                              {'name': 'ze6', 'value': 0.27722899999999984},
                              {'name': 'xe7', 'value': 0.76865},
                              {'name': 'ye7', 'value': 0.215177},
                              {'name': 'ze7', 'value': 0.888981},
                              {'name': 'xe8', 'value': 0.761848},
                              {'name': 'ye8', 'value': 0.508143},
                              {'name': 'ze8', 'value': 0.2745009999999999},
                              {'name': 'xe9', 'value': 0.695855},
                              {'name': 'ye9', 'value': 0.589422},
                              {'name': 'ze9', 'value': 0.43704999999999994},
                              {'name': 'xe10', 'value': 0.6914370000000001},
                              {'name': 'ye10', 'value': 0.736288},
                              {'name': 'ze10', 'value': 0.36462799999999984},
                              {'name': 'xe11', 'value': 0.646212},
                              {'name': 'ye11', 'value': 0.524822},
                              {'name': 'ze11', 'value': 0.842267},
                              {'name': 'xe12', 'value': 0.644476},
                              {'name': 'ye12', 'value': 0.185345},
                              {'name': 'ze12', 'value': -0.000248000000000026},
                              {'name': 'xe13', 'value': 0.52639},
                              {'name': 'ye13', 'value': 0.213948},
                              {'name': 'ze13', 'value': 0.8495199999999999},
                              {'name': 'xe14', 'value': 0.525862},
                              {'name': 'ye14', 'value': 0.645501},
                              {'name': 'ze14', 'value': 0.10287099999999982},
                              {'name': 'xe15', 'value': 0.524356},
                              {'name': 'ye15', 'value': 0.04622},
                              {'name': 'ze15', 'value': 0.24163899999999983}]},
        'Te': {'name': 'A_3_a_152',
               'spacegroup': 152,
               'wyckoffs': ['a'],
               'species': ['Te'],
               'parameters': [{'name': 'a', 'value': 4.5123742098481765},
                              {'name': 'c/a', 'value': 1.3207900592536466},
                              {'name': 'xa0', 'value': 0.26895}]}
    }
